name = "DASSL"
uuid = "e993076c-0cfd-5d6b-a1ac-36489fdf7917"
authors = ["Chris Rackauckas <accounts@chrisrackauckas.com>"]
version = "2.4.0"

[deps]
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
julia = "1"
DiffEqBase = "5"
